# Generated by Django 5.2.7 on 2026-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_alter_category_options_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
